export const challenges: any = [
  'Results summary component',
  { text: 'Product preview card component', href: 'product-preview-card' },
  'Skilled e-learning landing page',
  { text: 'Interactive rating component', href: 'interactive-rating' },
  { text: 'QR code component', href: 'qr-code' },
  { text: 'NFT preview card component', href: 'nft-preview-card' },
  'Equalizer landing page',
  { text: 'Order summary component', href: 'order-summary' },
  { text: 'Stats preview card component', href: 'stats-preview-card' },
  'Meet landing page',
  '3-column preview card component',
  'Pod request access landing page',
  { text: 'Profile card component', href: 'profile-card' },
  'FAQ accordion card',
  'Social proof section',
  { text: 'Article preview component', href: 'article-preview' },
  'Four card feature section',
  'Base Apparel coming soon page',
  { text: 'Intro component with sign-up form', href: 'intro-with-signup' },
  'Single price grid component',
  'Ping single column coming soon page',
  'Huddle landing page with a single introductory section',
  'Single-page developer portfolio',
  { text: 'News homepage', href: 'news-homepage' },
  'Notifications page',
  'Interactive card details form',
  'Single-page design portfolio',
  'Expenses chart component',
  'Intro section with dropdown navigation',
  { text: 'Advice generator app', href: 'advice-generator' },
  'Suite landing page',
  'Art gallery website',
  'Time tracking dashboard',
  'GitHub user search app',
  'Tip calculator app',
  'Sunnyside agency landing page',
  'Typemaster pre-launch landing page',
  'Blogr landing page',
  'Crowdfunding product page',
  'Interactive pricing component',
  'Maker pre-launch landing page',
  'Loopstudios landing page',
  'Officelite coming soon site',
  'Testimonials grid section',
  'Fylo data storage component',
  'Coding bootcamp testimonials slider',
  'Social media dashboard with theme switcher',
  'Insure landing page',
  'Pricing component with toggle',
  'Project tracking intro component',
  'Clipboard landing page',
  'Huddle landing page with alternating feature blocks',
  'Fylo dark theme landing page',
  'Fylo landing page with two column layout',
  'Huddle landing page with curved sections',
  'Dictionary web app',
  'Password generator app',
  'In-browser markdown editor',
  'Tic Tac Toe game',
  'Interactive comments section',
  'Space tourism multi-page website',
  'E-commerce product page',
  'Galleria slideshow site',
  'Planets fact site',
  'Calculator app',
  'Coffeeroasters subscription site',
  'Launch countdown timer',
  'Creative agency single-page site',
  'Todo app',
  'Clock app',
  'Room homepage',
  'IP Address Tracker',
  'Chat app CSS illustration',
  'Scoot multi-page website',
  'Dine restaurant website',
  'Minimalist portfolio website',
  'Job listings with filtering',
  'Easybank landing page',
  'Manage landing page',
  'URL shortening API landing page',
  'Bookmark landing page',
  'Multi-step form',
  'Connect Four game',
  'Entertainment web app',
  'Memory game',
  'Pomodoro app',
  'Devjobs web app',
  'PayAPI multi-page website',
  'Photosnap multi-page website',
  'Arch Studio multi-page website',
  'myteam multi-page website',
  'Rock, Paper, Scissors game',
  'REST Countries API with color theme switcher',
  'Kanban task management web app',
  'Product feedback app',
  'Audiophile e-commerce website',
  'Invoice app',
  'Designo multi-page website',
];
